version: 2

aliases:
  # machine
  - &build-machine
    macos:
      xcode: '9.3.0'
    shell: /bin/bash --login -eo pipefail
  # ruby gems
  - &restore-gem-cache
    keys:
      - v1-gems-{{ checksum "Gemfile.lock" }}
  - &install-gems
    name: install rubygems via Bundler
    command: bundle install --path vendor/bundle --clean
  - &save-gem-cache
    key: v1-gems-{{ checksum "Gemfile.lock" }}
    paths:
      - vendor/bundle
  # store artifacts
  - &ipa-artifacts
    path: "<PRODUCT NAME>".ipa
  - &dsym-artifacts
    path: "<PRODUCT NAME>".app.dSYM.zip

jobs:
  build:
    <<: *build-machine
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-gems
      - save_cache: *save-gem-cache
      - run: bundle exec fastlane test
  beta:
    <<: *build-machine
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-gems
      - save_cache: *save-gem-cache
      - run:
          name: distribute beta build to in-house users
          command: bundle exec fastlane beta
      - store_artifacts: *dsym-artifacts
      - store_artifacts: *ipa-artifacts
  deploy:
    <<: *build-machine
    steps:
      - checkout
      - restore_cache: *restore-gem-cache
      - run: *install-gems
      - save_cache: *save-gem-cache
      - run:
          name: deploy ipa file to iTunes Connect
          command: bundle exec fastlane deploy
      - store_artifacts: *dsym-artifacts
      - store_artifacts: *ipa-artifacts

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - beta:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
