version: 2

jobs:
  build:
    macos:
      xcode: '9.3.0'
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run: bundle exec fastlane test
  beta:
    macos:
      xcode: '9.3.0'
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: distribute beta build to in-house users
          command: bundle exec fastlane beta
      - store_artifacts:
          path: "<PRODUCT NAME>".app.dSYM.zip
      - store_artifacts:
          path: "<PRODUCT NAME>".ipa
  deploy:
    macos:
      xcode: '9.3.0'
    shell: /bin/bash --login -eo pipefail
    steps:
      - checkout
      - restore_cache:
          keys:
          - gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
      - run: bundle install --path vendor/bundle
      - save_cache:
          key: gem-cache-{{ arch }}-{{ checksum "Gemfile.lock" }}
          paths:
            - vendor/bundle
      - run:
          name: deploy ipa file to iTunes Connect
          command: bundle exec fastlane deploy
      - store_artifacts:
          path: "<PRODUCT NAME>".app.dSYM.zip
      - store_artifacts:
          path: "<PRODUCT NAME>".ipa

workflows:
  version: 2
  build-and-deploy:
    jobs:
      - build
      - beta:
          requires:
            - build
          filters:
            branches:
              only: develop
      - deploy:
          requires:
            - build
          filters:
            branches:
              only: master
