fastlane_version "1.48.0"

default_platform :ios

INFO_PLIST_FILE_PATH  = ''
BUILD_NUMBER          = ENV['CIRCLE_BUILD_NUM']

ARTIFACTS_PATH = ENV['CIRCLE_ARTIFACTS']

CRASHLYTICS_IPA_PATH      = ''
CRASHLYTICS_API_KEY       = ENV['CRASHLYTICS_API_KEY']
CRASHLYTICS_BUILD_SECRET  = ENV['CRASHLYTICS_BUILD_SECRET']
CRASHLYTICS_GROUP_ALIAS   = ENV['CRASHLYTICS_GROUP_ALIAS']

platform :ios do
  desc 'setup libraries'
  lane :setup do
    set_info_plist_value(path: INFO_PLIST_FILE_PATH, key: 'CFBundleVersion', value: BUILD_NUMBER) #updating build number
    cocoapods # execute if your project use CocoaPods and your repo does not include Pods directory
    carthage  # execute if your project use Carthage and your repo does not including Carthage/ directory
  end

  desc 'Runs all the tests'
  lane :test do
    scan
  end

  desc 'Distribute new ipa via beta app distribution service'
  lane :beta do
    match
    gym
    copy_artifacts(target_path: ARTIFACTS_PATH, artifacts: ["*.ipa", "*.dsym.zip"])
    crashlytics(api_token:    CRASHLYTICS_API_KEY,
                build_secret: CRASHLYTICS_BUILD_SECRET,
                ipa_path:     CRASHLYTICS_IPA_PATH,
                notes:        "Crashlytics Distribution message",
                groups:       CRASHLYTICS_GROUP_ALIAS)
  end

  desc 'Submit a new ipa file to iTunes Connect'
  lane :deploy do
    match
    gym
    copy_artifacts(target_path: ARTIFACTS_PATH, artifacts: ["*.ipa", "*.dsym.zip"])
    pilot(skip_submission: true,
          skip_waiting_for_build_processing: true)
  end
end
